# IAE - Analisis Exploratorio - General

In [1]:
#Realizo la llamada a los paquetes a Utilizar

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1. Lectura del Archivo

In [2]:
datos = pd.read_csv(r"C:\Users\User0044\Practica IAE\datos_IAE.csv",low_memory=False) #Realizo la lectura de CSV y lo asocio al DataFrame "datos"

In [3]:
datos.head() #Visualizo los primeros 5 valores del DataFrame

,SimTime,G_1200_EXTRA_Lev_BR001A,G_1200_EXTRA_Lev_BR001B,G_1200_EXTRA_Q_IAE,G_0690_TT_060300,G_0690_TT_060700,G_0690_TT_060800,G_0600_EXTRA_Lev_PRE,G_1090_FT_103111,G_1090_TT_103900,...,G_1200_ZSO_181350,G_1200_ZSO_181540,G_1200_ZSO_181550,G_1290_FSH_180900,G_1290_LSH_180100,G_1290_LSL_180540,G_1290_LSL_180550,G_1390_ZSC_191810,G_1390_ZSC_191910,Log
0,100,2.42,2.42,0.0,39.4721,43.0025,43.0025,12.597,3209.99,38.5843,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,NaN
1,200,2.42,2.42,0.0,39.4721,43.0025,43.0025,12.597,3209.99,38.5843,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,NaN
2,300,2.42,2.42,0.0,39.4721,43.0025,43.0025,12.597,3209.99,38.5843,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,NaN
3,400,2.42,2.42,0.0,39.4721,43.0025,43.0025,12.597,3209.99,38.5843,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,NaN
4,500,2.42,2.42,0.0,39.4721,43.0025,43.0025,12.597,3209.99,38.5843,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,NaN

In [5]:
datos.tail()

,SimTime,G_1200_EXTRA_Lev_BR001A,G_1200_EXTRA_Lev_BR001B,G_1200_EXTRA_Q_IAE,G_0690_TT_060300,G_0690_TT_060700,G_0690_TT_060800,G_0600_EXTRA_Lev_PRE,G_1090_FT_103111,G_1090_TT_103900,...,G_1200_ZSO_181350,G_1200_ZSO_181540,G_1200_ZSO_181550,G_1290_FSH_180900,G_1290_LSH_180100,G_1290_LSL_180540,G_1290_LSL_180550,G_1390_ZSC_191810,G_1390_ZSC_191910,Log
1048557,104877700,0.648538,0.648536,1.03967,10.8358,10.8358,10.8358,5.89994,0.0,81.9169,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
1048558,104877800,0.648536,0.648534,1.03967,10.8359,10.8359,10.8359,5.89994,0.0,81.9185,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
1048559,104877900,0.648534,0.648532,1.03966,10.8359,10.8359,10.8359,5.89994,0.0,81.9202,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
1048560,104878000,0.648532,0.648530,1.03967,10.8359,10.8359,10.8359,5.89994,0.0,81.9218,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
1048561,104878100,0.648530,0.648528,1.03967,10.8359,10.8359,10.8359,5.89995,0.0,81.9234,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN

## 2. Visualizacion General del DataFrame

In [6]:
datos.info() #Rralizo una Visualizacion general del DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048562 entries, 0 to 1048561
Data columns (total 30 columns):
SimTime                     1048562 non-null object
G_1200_EXTRA_Lev_BR001A     1047889 non-null float64
G_1200_EXTRA_Lev_BR001B     1047889 non-null float64
G_1200_EXTRA_Q_IAE          1047889 non-null float64
G_0690_TT_060300            1047889 non-null float64
G_0690_TT_060700            1047889 non-null float64
G_0690_TT_060800            1047889 non-null float64
G_0600_EXTRA_Lev_PRE        1047889 non-null float64
G_1090_FT_103111            1047889 non-null float64
G_1090_TT_103900            1047889 non-null float64
G_1090_TT_105210            1047889 non-null float64
G_0100_EXTRA_Pot_Total      1047889 non-null float64
G_1000_EXTRA_QNucleo        1047889 non-null float64
G_1000_EXTRA_Tout_Nucleo    1047889 non-null float64
G_1000_EXTRA_Tin_Nucleo     1047889 non-null float64
G_1000_EXTRA_QChimenea      1047889 non-null float64
G_1000_EXTRA_QClapeta       1047889 non-null float64
G_1200_ZSC_181300           1047889 non-null float64
G_1200_ZSC_181500           1047889 non-null float64
G_1200_ZSO_181340           1047889 non-null float64
G_1200_ZSO_181350           1047889 non-null float64
G_1200_ZSO_181540           1047889 non-null float64
G_1200_ZSO_181550           1047889 non-null float64
G_1290_FSH_180900           1047889 non-null float64
G_1290_LSH_180100           1047889 non-null float64
G_1290_LSL_180540           1047889 non-null float64
G_1290_LSL_180550           1047889 non-null float64
G_1390_ZSC_191810           1047889 non-null float64
G_1390_ZSC_191910           1047889 non-null float64
Log                         0 non-null float64
dtypes: float64(29), object(1)
memory usage: 240.0+ MB

In [7]:
datos.columns #Visualizo las columnas del DataFrame

Index(['SimTime', 'G_1200_EXTRA_Lev_BR001A', 'G_1200_EXTRA_Lev_BR001B',
       'G_1200_EXTRA_Q_IAE', 'G_0690_TT_060300', 'G_0690_TT_060700',
       'G_0690_TT_060800', 'G_0600_EXTRA_Lev_PRE', 'G_1090_FT_103111',
       'G_1090_TT_103900', 'G_1090_TT_105210', 'G_0100_EXTRA_Pot_Total',
       'G_1000_EXTRA_QNucleo', 'G_1000_EXTRA_Tout_Nucleo',
       'G_1000_EXTRA_Tin_Nucleo', 'G_1000_EXTRA_QChimenea',
       'G_1000_EXTRA_QClapeta', 'G_1200_ZSC_181300', 'G_1200_ZSC_181500',
       'G_1200_ZSO_181340', 'G_1200_ZSO_181350', 'G_1200_ZSO_181540',
       'G_1200_ZSO_181550', 'G_1290_FSH_180900', 'G_1290_LSH_180100',
       'G_1290_LSL_180540', 'G_1290_LSL_180550', 'G_1390_ZSC_191810',
       'G_1390_ZSC_191910', 'Log'],
      dtype='object')

In [8]:
datos.dtypes #Tipos de datos de cada columna

SimTime                      object
G_1200_EXTRA_Lev_BR001A     float64
G_1200_EXTRA_Lev_BR001B     float64
G_1200_EXTRA_Q_IAE          float64
G_0690_TT_060300            float64
G_0690_TT_060700            float64
G_0690_TT_060800            float64
G_0600_EXTRA_Lev_PRE        float64
G_1090_FT_103111            float64
G_1090_TT_103900            float64
G_1090_TT_105210            float64
G_0100_EXTRA_Pot_Total      float64
G_1000_EXTRA_QNucleo        float64
G_1000_EXTRA_Tout_Nucleo    float64
G_1000_EXTRA_Tin_Nucleo     float64
G_1000_EXTRA_QChimenea      float64
G_1000_EXTRA_QClapeta       float64
G_1200_ZSC_181300           float64
G_1200_ZSC_181500           float64
G_1200_ZSO_181340           float64
G_1200_ZSO_181350           float64
G_1200_ZSO_181540           float64
G_1200_ZSO_181550           float64
G_1290_FSH_180900           float64
G_1290_LSH_180100           float64
G_1290_LSL_180540           float64
G_1290_LSL_180550           float64
G_1390_ZSC_191810           float64
G_1390_ZSC_191910           float64
Log                         float64
dtype: object

## 3. Analisis de valores Nulos

In [9]:
datos.isnull().sum() #Cuento la cantidad de nulos que tiene cada columna

SimTime                           0
G_1200_EXTRA_Lev_BR001A         673
G_1200_EXTRA_Lev_BR001B         673
G_1200_EXTRA_Q_IAE              673
G_0690_TT_060300                673
G_0690_TT_060700                673
G_0690_TT_060800                673
G_0600_EXTRA_Lev_PRE            673
G_1090_FT_103111                673
G_1090_TT_103900                673
G_1090_TT_105210                673
G_0100_EXTRA_Pot_Total          673
G_1000_EXTRA_QNucleo            673
G_1000_EXTRA_Tout_Nucleo        673
G_1000_EXTRA_Tin_Nucleo         673
G_1000_EXTRA_QChimenea          673
G_1000_EXTRA_QClapeta           673
G_1200_ZSC_181300               673
G_1200_ZSC_181500               673
G_1200_ZSO_181340               673
G_1200_ZSO_181350               673
G_1200_ZSO_181540               673
G_1200_ZSO_181550               673
G_1290_FSH_180900               673
G_1290_LSH_180100               673
G_1290_LSL_180540               673
G_1290_LSL_180550               673
G_1390_ZSC_191810               673
G_1390_ZSC_191910               673
Log                         1048562
dtype: int64

Segun se observa la columna Log tiene una cantidad muy grande de nulos, los cuales seguramente corresponden a los datos correspondiente a OOS (out of scope) del Simulador. Por este motivo procedo a borrar esta columna por completo:

In [10]:
datos_new = datos.drop("Log",axis=1)

In [11]:
datos_new.info() #Verifico que la columna "Log" se borro

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048562 entries, 0 to 1048561
Data columns (total 29 columns):
SimTime                     1048562 non-null object
G_1200_EXTRA_Lev_BR001A     1047889 non-null float64
G_1200_EXTRA_Lev_BR001B     1047889 non-null float64
G_1200_EXTRA_Q_IAE          1047889 non-null float64
G_0690_TT_060300            1047889 non-null float64
G_0690_TT_060700            1047889 non-null float64
G_0690_TT_060800            1047889 non-null float64
G_0600_EXTRA_Lev_PRE        1047889 non-null float64
G_1090_FT_103111            1047889 non-null float64
G_1090_TT_103900            1047889 non-null float64
G_1090_TT_105210            1047889 non-null float64
G_0100_EXTRA_Pot_Total      1047889 non-null float64
G_1000_EXTRA_QNucleo        1047889 non-null float64
G_1000_EXTRA_Tout_Nucleo    1047889 non-null float64
G_1000_EXTRA_Tin_Nucleo     1047889 non-null float64
G_1000_EXTRA_QChimenea      1047889 non-null float64
G_1000_EXTRA_QClapeta       1047889 non-null float64
G_1200_ZSC_181300           1047889 non-null float64
G_1200_ZSC_181500           1047889 non-null float64
G_1200_ZSO_181340           1047889 non-null float64
G_1200_ZSO_181350           1047889 non-null float64
G_1200_ZSO_181540           1047889 non-null float64
G_1200_ZSO_181550           1047889 non-null float64
G_1290_FSH_180900           1047889 non-null float64
G_1290_LSH_180100           1047889 non-null float64
G_1290_LSL_180540           1047889 non-null float64
G_1290_LSL_180550           1047889 non-null float64
G_1390_ZSC_191810           1047889 non-null float64
G_1390_ZSC_191910           1047889 non-null float64
dtypes: float64(28), object(1)
memory usage: 232.0+ MB

## 4. Configuracion Columna "Tiempo"

In [12]:
x = datos_new["SimTime"]
y = datos_new["G_1200_EXTRA_Lev_BR001A"]

In [ ]:
plt.plot(x,y)
plt.show()